port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: d300ae15-2ba2-4f91-b1b0-b4510912e4cc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /admin
    headers:
      Host: 2free2.aparatir.xyz
  servername: 2free2.aparatir.xyz
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: 101reel.com
  port: 80
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@MARAMBASHI_MARAMBASHI_MARAMBASHI
    headers:
      Host: havvas.shohreh.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: 62.60.233.250
  port: 443
  uuid: fd0cdd44-2361-11f0-9970-45e1d80c4039
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: kernel.panel.cactusv2.xyz
  port: 4434
  uuid: 346264b7-975c-4891-8f7b-dcd6e5707a42
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: viop.fast.hosting-ip.com
  port: 80
  uuid: 7fa08b3d-86d8-4b14-92b3-4c56a83f027d
  cipher: none
  tls: false
  network: xhttp
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: all32-vip.f-sub.com
  port: 2434
  uuid: 738c5a04-817a-4f50-b327-893595010155
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 91.99.190.38
  port: 51615
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: c51.aminzing.lol
  port: 443
  uuid: 2de98c6e-319d-4fd1-81ba-82237c44ed36
  cipher: none
  tls: true
  network: httpupgrade
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: 104.18.82.55
  port: 443
  uuid: 29187857-4a1f-4d1e-88eb-0016771e0dbb
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
  servername: vless.hubp.de
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: 194.87.245.123
  port: 443
  uuid: 677615f7-87d5-5019-a44d-4fc3ff8d59d7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: 188.68.53.100
  port: 6666
  uuid: 0abf9050-c7be-464d-80af-24094c2b97de
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: 5.189.190.60
  port: 34704
  uuid: 69394f3f-e84c-44b3-96ae-46000130cf2b
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: 94.131.9.77
  port: 443
  uuid: 677615f7-87d5-5019-a44d-4fc3ff8d59d7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: cdn.413918.xyz
  port: 40061
  uuid: 11db0644-edeb-442c-bd42-e5ea58ea7395
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 185.242.84.181
  port: 443
  uuid: 677615f7-87d5-5019-a44d-4fc3ff8d59d7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: fin.monkeyisland.life
  port: 443
  uuid: 74c0af7c-8482-4b4e-b067-ea456a80cdb7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: 77.110.102.49
  port: 443
  uuid: 677615f7-87d5-5019-a44d-4fc3ff8d59d7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: 77.110.105.19
  port: 443
  uuid: 677615f7-87d5-5019-a44d-4fc3ff8d59d7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: 45.84.0.57
  port: 443
  uuid: 677615f7-87d5-5019-a44d-4fc3ff8d59d7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: 5.182.37.94
  port: 443
  uuid: 677615f7-87d5-5019-a44d-4fc3ff8d59d7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: usa.savanet.pro
  port: 443
  uuid: 87eff1bd-d55f-4df2-a5ad-863368a16cb7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: freeyx.cloudflare88.eu.org
  port: 443
  uuid: 1955487c-1f99-45df-867f-04bfbbf28f8d
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /announcement?ed=2048fp=random
    headers:
      Host: oracle-kr-chuncheon.862400.xyz
  servername: oracle-kr-chuncheon.862400.xyz
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: freeyx.cloudflare88.eu.org
  port: 443
  uuid: 1955487c-1f99-45df-867f-04bfbbf28f8d
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /announcementfp=random
    headers:
      Host: oracle-kr-chuncheon.862400.xyz
  servername: oracle-kr-chuncheon.862400.xyz
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: cent1de.maga171717.sbs
  port: 443
  uuid: 706fae5e-3fc6-41a4-8eb7-3b3df7bad72b
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: 199.34.230.114
  port: 2053
  uuid: b27e35a7-51f4-468e-8921-56a4901dd923
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /containers/defp=chrome
    headers:
      Host: om1.omidsuccess.uk
  servername: om1.omidsuccess.uk
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
