port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 25.129.199.156
  port: 8880
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: kjgx.laoyoutiao.link
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: elegant-corporation.seotoolsforyou.co.uk
  port: 80
  uuid: d03d8815-a06f-408f-a62f-6c84869b96a9
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?--@FREEV2RNG--Bia-FREEV2rng--Kanal-@FREEv2RNG--
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: jealous-competition.seotoolsforyou.co.uk
  port: 80
  uuid: 7094df26-af60-41c4-afac-857060d1bab0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?serverrrVPNTELEGRAM---_@vpnserverrr_@vpnserverrr_@vpnserverrr_@vpnserverrr_@vpnserverrr
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: magical-fish.seotoolsforyou.co.uk
  port: 80
  uuid: edb4c373-ac92-4430-8f42-94439ca829b9
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?--/V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS---V2RAYNG_FARS
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: wonderful-degree.seotoolsforyou.co.uk
  port: 80
  uuid: 6192c1d9-5ae1-40ba-9cbb-cfacc2f8533c
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: 104.26.14.69
  port: 2096
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: fierce-data.seotoolsforyou.co.uk
  port: 80
  uuid: c313c27c-97ff-45ed-ab5c-64641af5debc
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: 172.67.164.5
  port: 443
  uuid: ec7de7e0-3f09-4ef4-8a34-e441917d65fa
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: verina.ccantarella.dns-dynamic.net
  servername: verina.ccantarella.dns-dynamic.net
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: obedient-detail.seotoolsforyou.co.uk
  port: 80
  uuid: 1dd49fb8-6570-4a2a-a236-f410b63159cf
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 172.67.164.1
  port: 443
  uuid: ec7de7e0-3f09-4ef4-8a34-e441917d65fa
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: verina.ccantarella.dns-dynamic.net
  servername: verina.ccantarella.dns-dynamic.net
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: sweet-combination.seotoolsforyou.co.uk
  port: 80
  uuid: 05020a61-3c0c-4ead-b256-7851ff905a75
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 25.25.25.188
  port: 8880
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ip.langmanshanxi.top
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: www.ums.id
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: 104.16.161.143
  port: 2096
  uuid: f690c2da-bdc3-4538-999e-d2bb8a541188
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed
    headers:
      Host: baomei.pages.dev
  servername: baomei.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: bewildered-poem.seotoolsforyou.co.uk
  port: 80
  uuid: 0f4865d9-9405-4703-a282-46e326e6d9e7
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: 104.26.14.69
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: privasi.turah.my.id
  port: 443
  uuid: 0fbf4f81-2598-4b6a-a623-0ead4cb9efa8
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /Free-CF-Proxy-AD192.3.113.4-19318
    headers:
      Host: privasi.turah.my.id
  servername: privasi.turah.my.id
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: 104.21.67.12
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 104.16.108.84
  port: 443
  uuid: a89357b8-a501-46bd-ac6d-c0f37f1fd0f5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: shutu.pages.dev
  servername: shutu.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: 45.131.4.85
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: pqh25v7.waipdirect.shop
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: deu246.bypassall.org
  port: 443
  uuid: b4b8aa1f-77d2-4851-a5a4-f78886f3e997
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: fina.iranbuildings.com
  port: 8444
  uuid: ac083fa9-df9a-4722-b70d-24c17bef0516
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: 158.41.110.94
  port: 34045
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: cdn28.saloonak.ir
  port: 8443
  uuid: 789d4f30-c31b-4762-8116-ed42574d5e85
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: 193.151.135.21
  port: 44443
  uuid: 53fff6cc-b4ec-43e8-ade5-e0c42972fc33
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: hybrid.arvancloud.online
  port: 44443
  uuid: 53fff6cc-b4ec-43e8-ade5-e0c42972fc33
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: 104.21.48.1
  port: 443
  uuid: e5c2e234-333e-48b4-8199-2793a64527bc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /fp=chrome
    headers:
      Host: s1-c3r.pages.dev
  servername: s1-c3r.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: aio.xtradata.dpdns.org
  port: 443
  uuid: f282b878-8711-45a1-8c69-5564172123c1
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /aioproxybot/129.150.49.58-18650fp=chrome
    headers:
      Host: aio.xtradata.dpdns.org
  servername: aio.xtradata.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-31
  type: vless
  server: tgju.org
  port: 80
  uuid: 2b277eea-66b2-4f3a-b934-46225c1f5e6f
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: SeRvER02.VtNEt.InFO
- name: ğŸŒ ASTRACAT-Tunels-32
  type: vless
  server: 104.21.28.82
  port: 443
  uuid: 71504eaf-29ac-4190-89d1-dd9ce2c9ee14
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /fp=chrome
    headers:
      Host: backhaxus.dh04.shop
  servername: backhaxus.dh04.shop
- name: ğŸŒ ASTRACAT-Tunels-33
  type: vless
  server: 63.141.128.14
  port: 80
  uuid: 18494a96-f6a7-425d-ae82-dc00c4f3f819
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Join-ZEDMODEON-ZEDMODEON-ZEDMODEON-bia-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON
    headers:
      Host: a.joIn.zEdMoDeOn.oNl.
- name: ğŸŒ ASTRACAT-Tunels-34
  type: vless
  server: 63.141.128.28
  port: 8080
  uuid: 49e77ea9-62bd-44c4-8a52-0d7569c305c5
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Join-ZEDMODEON-ZEDMODEON-ZEDMODEON-bia-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON
    headers:
      Host: f.jOin.zEdMoDeOn.oNl.
- name: ğŸŒ ASTRACAT-Tunels-35
  type: vless
  server: 63.141.128.16
  port: 8080
  uuid: a82def0b-92c5-450b-9fca-7f1b7f932e8e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Join-ZEDMODEON-ZEDMODEON-ZEDMODEON-bia-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON
    headers:
      Host: e.jOin.zEdMoDeOn.oNl.
- name: ğŸŒ ASTRACAT-Tunels-36
  type: vless
  server: 63.141.128.15
  port: 8080
  uuid: cf6deb67-e7a5-4a8d-bc8e-11efd14817cc
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Join-ZEDMODEON-ZEDMODEON-ZEDMODEON-bia-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON
    headers:
      Host: d.jOin.zEdMoDeOn.oNl.
- name: ğŸŒ ASTRACAT-Tunels-37
  type: vless
  server: 63.141.128.13
  port: 80
  uuid: fdf5ef4d-bf23-4bd1-b04e-39c80ba0c577
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Join-ZEDMODEON-ZEDMODEON-ZEDMODEON-bia-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON
    headers:
      Host: c.jOin.zEdMoDeOn.oNl.
- name: ğŸŒ ASTRACAT-Tunels-38
  type: vless
  server: 159.112.235.174
  port: 2082
  uuid: 47e9a0db-50c6-4522-8819-502c55b06dde
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: workerr.schodog1.workers.dev
- name: ğŸŒ ASTRACAT-Tunels-39
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
  - ğŸŒ ASTRACAT-Tunels-31
  - ğŸŒ ASTRACAT-Tunels-32
  - ğŸŒ ASTRACAT-Tunels-33
  - ğŸŒ ASTRACAT-Tunels-34
  - ğŸŒ ASTRACAT-Tunels-35
  - ğŸŒ ASTRACAT-Tunels-36
  - ğŸŒ ASTRACAT-Tunels-37
  - ğŸŒ ASTRACAT-Tunels-38
  - ğŸŒ ASTRACAT-Tunels-39
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
