port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 129.80.237.223
  port: 443
  uuid: ccff34b1-44fd-478d-bc0e-5111cb11f5be
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cr777.medicaldream.ir
  servername: cr777.medicaldream.ir
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 199.34.228.169
  port: 443
  uuid: 2fec7227-9abe-46f2-af18-78302b836c45
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /qF5dXhCllosLcFpqdDoAgkondVWl
    headers:
      Host: 3u.2031.pp.ua
  servername: 3u.2031.pp.ua
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: 15.236.162.49
  port: 22223
  uuid: telegram-id-directvpn
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: premium.vkehi.shop
  port: 443
  uuid: 355d36aa-9ac0-4865-9f51-df2a0a506e64
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
