port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 25.129.199.122
  port: 2096
  uuid: 2fb8808b-b94c-42ea-9dd2-cd77d2efcc8d
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /eyJqdW5rIjoidDZLaDRBMWhpIiwicHJvdG9jb2wiOiJ2bCIsIm1vZGUiOiJwcm94eWlwIiwicGFuZWxJUHMiOltdfQ
    headers:
      Host: digikalaa.dpdns.org
  servername: DiGIkALaA.dpdns.ORG
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: DEADSEECtelegram.blackandwhiteshop.ir
  port: 80
  uuid: cbadfd29-8352-46e5-8baa-0010b43d1059
  cipher: none
  tls: false
  network: xhttp
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: DEADSEECtelegram.blackandwhiteshop.ir
  port: 80
  uuid: cbadfd29-8352-46e5-8baa-0010b43d1059
  cipher: none
  tls: false
  network: xhttp
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: 25.129.197.138
  port: 2053
  uuid: 8a07740f-b932-4372-a3a2-ed91f184cd33
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /eyJqdW5rIjoiNDBNWGY3Z0NPd0loZ2YiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: khamenei.dpdns.org
  servername: KhAmeneI.DPdNs.OrG
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
