port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 25.129.197.138
  port: 2053
  uuid: 8a07740f-b932-4372-a3a2-ed91f184cd33
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /eyJqdW5rIjoiNDBNWGY3Z0NPd0loZ2YiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: khamenei.dpdns.org
  servername: KhAmeneI.DPdNs.OrG
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
