port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: d300ae15-2ba2-4f91-b1b0-b4510912e4cc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /admin
    headers:
      Host: 2free2.aparatir.xyz
  servername: 2free2.aparatir.xyz
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: 101reel.com
  port: 80
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@MARAMBASHI_MARAMBASHI_MARAMBASHI
    headers:
      Host: havvas.shohreh.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: 62.60.233.250
  port: 443
  uuid: fd0cdd44-2361-11f0-9970-45e1d80c4039
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: kernel.panel.cactusv2.xyz
  port: 4434
  uuid: 346264b7-975c-4891-8f7b-dcd6e5707a42
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: viop.fast.hosting-ip.com
  port: 80
  uuid: 7fa08b3d-86d8-4b14-92b3-4c56a83f027d
  cipher: none
  tls: false
  network: xhttp
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: all32-vip.f-sub.com
  port: 2434
  uuid: 738c5a04-817a-4f50-b327-893595010155
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 91.99.190.38
  port: 51615
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: c51.aminzing.lol
  port: 443
  uuid: 2de98c6e-319d-4fd1-81ba-82237c44ed36
  cipher: none
  tls: true
  network: httpupgrade
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: 104.26.14.69
  port: 2096
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: fierce-data.seotoolsforyou.co.uk
  port: 80
  uuid: c313c27c-97ff-45ed-ab5c-64641af5debc
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: 172.67.164.5
  port: 443
  uuid: ec7de7e0-3f09-4ef4-8a34-e441917d65fa
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: verina.ccantarella.dns-dynamic.net
  servername: verina.ccantarella.dns-dynamic.net
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: obedient-detail.seotoolsforyou.co.uk
  port: 80
  uuid: 1dd49fb8-6570-4a2a-a236-f410b63159cf
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: 172.67.164.1
  port: 443
  uuid: ec7de7e0-3f09-4ef4-8a34-e441917d65fa
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: verina.ccantarella.dns-dynamic.net
  servername: verina.ccantarella.dns-dynamic.net
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: sweet-combination.seotoolsforyou.co.uk
  port: 80
  uuid: 05020a61-3c0c-4ead-b256-7851ff905a75
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 25.25.25.188
  port: 8880
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ip.langmanshanxi.top
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: www.ums.id
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: 104.16.161.143
  port: 2096
  uuid: f690c2da-bdc3-4538-999e-d2bb8a541188
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed
    headers:
      Host: baomei.pages.dev
  servername: baomei.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: bewildered-poem.seotoolsforyou.co.uk
  port: 80
  uuid: 0f4865d9-9405-4703-a282-46e326e6d9e7
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: 104.26.14.69
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: privasi.turah.my.id
  port: 443
  uuid: 0fbf4f81-2598-4b6a-a623-0ead4cb9efa8
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /Free-CF-Proxy-AD192.3.113.4-19318
    headers:
      Host: privasi.turah.my.id
  servername: privasi.turah.my.id
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: 104.21.67.12
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: 104.16.108.84
  port: 443
  uuid: a89357b8-a501-46bd-ac6d-c0f37f1fd0f5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: shutu.pages.dev
  servername: shutu.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: 45.131.4.85
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: pqh25v7.waipdirect.shop
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: 194.156.65.28
  port: 443
  uuid: 21792da3-074f-4d55-8a6b-4d84c5c0f682
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-31
  type: vless
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  port: 443
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-32
  type: vless
  server: 178.17.58.126
  port: 443
  uuid: 6035325d-399a-5148-9126-29cedfd5966a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-33
  type: vless
  server: hybrid.arvancloud.online
  port: 44443
  uuid: 53fff6cc-b4ec-43e8-ade5-e0c42972fc33
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-34
  type: vless
  server: 193.151.135.21
  port: 44443
  uuid: 53fff6cc-b4ec-43e8-ade5-e0c42972fc33
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-35
  type: vless
  server: 185.18.184.66
  port: 80
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /ğŸ”’
    headers:
      Host: hello.96xckkzx.workers.dev
- name: ğŸŒ ASTRACAT-Tunels-36
  type: vless
  server: 159.112.235.174
  port: 2082
  uuid: 47e9a0db-50c6-4522-8819-502c55b06dde
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: workerr.schodog1.workers.dev
- name: ğŸŒ ASTRACAT-Tunels-37
  type: vless
  server: 104.21.81.174
  port: 80
  uuid: 23b3cbba-e6ac-485a-9481-342a0415eab9
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /wP3dwCyRAVyMJFfW?ed=2560
    headers:
      Host: DaWn-lAKE-d5E3.WocoYA4320.wOrkERs.DeV
- name: ğŸŒ ASTRACAT-Tunels-38
  type: vless
  server: 104.21.7.50
  port: 2052
  uuid: 0d710c53-876d-401f-97f0-6bd1a8db941a
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: sWEeT-DIsK-b69d.TUdTudtrUHtRU.wOrkERS.dev
- name: ğŸŒ ASTRACAT-Tunels-39
  type: vless
  server: 63.141.128.34
  port: 80
  uuid: 2f2327bd-ff1b-4ce5-bf86-fe0565334138
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Join-ZEDMODEON-ZEDMODEON-ZEDMODEON-bia-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON-ZEDMODEON
    headers:
      Host: b.jOin.zEdMoDeOn.oNl.
- name: ğŸŒ ASTRACAT-Tunels-40
  type: vless
  server: 198.62.62.2
  port: 443
  uuid: 598b4251-fd03-48fe-b12d-630ac3adf2e5
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /hjgfdwssecurity=tls
    headers:
      Host: smn2.gerlemondns.info
- name: ğŸŒ ASTRACAT-Tunels-41
  type: vless
  server: 172.233.201.93
  port: 34045
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-42
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
  - ğŸŒ ASTRACAT-Tunels-31
  - ğŸŒ ASTRACAT-Tunels-32
  - ğŸŒ ASTRACAT-Tunels-33
  - ğŸŒ ASTRACAT-Tunels-34
  - ğŸŒ ASTRACAT-Tunels-35
  - ğŸŒ ASTRACAT-Tunels-36
  - ğŸŒ ASTRACAT-Tunels-37
  - ğŸŒ ASTRACAT-Tunels-38
  - ğŸŒ ASTRACAT-Tunels-39
  - ğŸŒ ASTRACAT-Tunels-40
  - ğŸŒ ASTRACAT-Tunels-41
  - ğŸŒ ASTRACAT-Tunels-42
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
