port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: d300ae15-2ba2-4f91-b1b0-b4510912e4cc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /admin
    headers:
      Host: 2free2.aparatir.xyz
  servername: 2free2.aparatir.xyz
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: 101reel.com
  port: 80
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@MARAMBASHI_MARAMBASHI_MARAMBASHI
    headers:
      Host: havvas.shohreh.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: 62.60.233.250
  port: 443
  uuid: fd0cdd44-2361-11f0-9970-45e1d80c4039
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: kernel.panel.cactusv2.xyz
  port: 4434
  uuid: 346264b7-975c-4891-8f7b-dcd6e5707a42
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: viop.fast.hosting-ip.com
  port: 80
  uuid: 7fa08b3d-86d8-4b14-92b3-4c56a83f027d
  cipher: none
  tls: false
  network: xhttp
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: all32-vip.f-sub.com
  port: 2434
  uuid: 738c5a04-817a-4f50-b327-893595010155
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 91.99.190.38
  port: 51615
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: c51.aminzing.lol
  port: 443
  uuid: 2de98c6e-319d-4fd1-81ba-82237c44ed36
  cipher: none
  tls: true
  network: httpupgrade
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: 104.26.14.69
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: privasi.turah.my.id
  port: 443
  uuid: 0fbf4f81-2598-4b6a-a623-0ead4cb9efa8
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /Free-CF-Proxy-AD192.3.113.4-19318
    headers:
      Host: privasi.turah.my.id
  servername: privasi.turah.my.id
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: 104.21.67.12
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: 104.16.108.84
  port: 443
  uuid: a89357b8-a501-46bd-ac6d-c0f37f1fd0f5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: shutu.pages.dev
  servername: shutu.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: 45.131.4.85
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: pqh25v7.waipdirect.shop
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: 5.10.214.253
  port: 2096
  uuid: 7556317c-dff6-46e8-ad29-b408f2a6456e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Telegram @freecodes /?ed=2560security=tls
    headers:
      Host: vless.muzheng.top
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: 218.154.22.99
  port: 50003
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /X@èŠ‚ç‚¹ç‹‚é­”/?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: 211.48.77.114
  port: 12312
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /x @èŠ‚ç‚¹ç‹‚é­”security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: 118.41.28.45
  port: 50001
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /telegram @freecodessecurity=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: 119.195.219.150
  port: 10065
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /telegram @freecodessecurity=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: 220.118.236.239
  port: 12290
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /x @èŠ‚ç‚¹ç‹‚é­”security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: 211.228.5.119
  port: 50001
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /x @èŠ‚ç‚¹ç‹‚é­”security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: 220.126.185.107
  port: 50001
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /x @èŠ‚ç‚¹ç‹‚é­”security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: 211.184.175.180
  port: 50001
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /telegram @freecodessecurity=tlssecurity=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: 112.156.154.95
  port: 30067
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /x @èŠ‚ç‚¹ç‹‚é­”security=tlssecurity=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: 112.156.154.95
  port: 30067
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /x @èŠ‚ç‚¹ç‹‚é­”security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-31
  type: vless
  server: 119.65.139.101
  port: 60001
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /x@èŠ‚ç‚¹ç‹‚é­”security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-32
  type: vless
  server: 194.152.44.253
  port: 2096
  uuid: 7556317c-dff6-46e8-ad29-b408f2a6456e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Telegram @freecodes /?ed=2560security=tls
    headers:
      Host: vless.muzheng.top
- name: ğŸŒ ASTRACAT-Tunels-33
  type: vless
  server: 185.18.184.253
  port: 2096
  uuid: 7556317c-dff6-46e8-ad29-b408f2a6456e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560security=tls
    headers:
      Host: vless.muzheng.top
- name: ğŸŒ ASTRACAT-Tunels-34
  type: vless
  server: 185.18.184.253
  port: 2096
  uuid: 7556317c-dff6-46e8-ad29-b408f2a6456e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /telegram@freecodessecurity=tls
    headers:
      Host: vless.muzheng.top
- name: ğŸŒ ASTRACAT-Tunels-35
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@freecodes/?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-36
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramU0001F1E8U0001F1F3@WangCai2/?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-37
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramğŸ‡¨ğŸ‡³ @WangCai2 /?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-38
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramU0001F1E8U0001F1F3 @WangCai2 /?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-39
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /freecodes@èŠ‚ç‚¹ç‹‚é­”/?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-40
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-41
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramU0001F1E8U0001F1F3 @WangCai2security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-42
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /security=tlssecurity=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-43
  type: vless
  server: 188.42.145.253
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-44
  type: vless
  server: 167.179.27.92
  port: 443
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-45
  type: vless
  server: 104.19.50.238
  port: 2096
  uuid: f61a4285-7264-4d07-9408-7b9ba1922c26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /telegramğŸ‡¨ğŸ‡³@wangcai2/?ed=2560security=tls
    headers:
      Host: gaosir.unfeeling.sbs
- name: ğŸŒ ASTRACAT-Tunels-46
  type: vless
  server: 104.20.2.221
  port: 8443
  uuid: 6c7a6a6a-6a6a-4000-8000-000000000002
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560fp=chrome
    headers:
      Host: bycf.lzjnb.shop
  servername: bycf.lzjnb.shop
- name: ğŸŒ ASTRACAT-Tunels-47
  type: vless
  server: 54.219.42.163
  port: 443
  uuid: da640c05-1831-4c6f-a2c8-ff8ff9c18b0c
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-48
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
  - ğŸŒ ASTRACAT-Tunels-31
  - ğŸŒ ASTRACAT-Tunels-32
  - ğŸŒ ASTRACAT-Tunels-33
  - ğŸŒ ASTRACAT-Tunels-34
  - ğŸŒ ASTRACAT-Tunels-35
  - ğŸŒ ASTRACAT-Tunels-36
  - ğŸŒ ASTRACAT-Tunels-37
  - ğŸŒ ASTRACAT-Tunels-38
  - ğŸŒ ASTRACAT-Tunels-39
  - ğŸŒ ASTRACAT-Tunels-40
  - ğŸŒ ASTRACAT-Tunels-41
  - ğŸŒ ASTRACAT-Tunels-42
  - ğŸŒ ASTRACAT-Tunels-43
  - ğŸŒ ASTRACAT-Tunels-44
  - ğŸŒ ASTRACAT-Tunels-45
  - ğŸŒ ASTRACAT-Tunels-46
  - ğŸŒ ASTRACAT-Tunels-47
  - ğŸŒ ASTRACAT-Tunels-48
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
