port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 34.228.235.1
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 54.80.121.136
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: 104.17.148.22
  port: 80
  uuid: 9e85b4eb-f53d-457e-9385-454db3c1dcc1
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: 5.104.75.130
  port: 8443
  uuid: 9e769ce1-34be-4e3f-b0a6-823f30eb8f69
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: fp=chrome
    headers:
      Host: CiR346yL3b.DeRaKhT.iNfO
  servername: CiR346yL3b.DeRaKhT.iNfO
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: whatismyipaddress.com
  port: 2096
  uuid: 2404f667-5969-4883-a71a-ea2e0db2d25b
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: fp=chrome
    headers:
      Host: wwwspeedtestnetwhiteberinsistomd6625996s16.yozpalangserver.ir
  servername: wwwspeedtestnetwhiteberinsistomd6625996s16.yozpalangserver.ir
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: whatismyipaddress.com
  port: 2096
  uuid: 2404f667-5969-4883-a71a-ea2e0db2d25b
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: fp=chrome
    headers:
      Host: wwwspeedtestnetwhiteberinsistomd6625996s09.gorgeserver1.ir
  servername: wwwspeedtestnetwhiteberinsistomd6625996s09.gorgeserver1.ir
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: 176.223.66.8
  port: 39948
  uuid: 2558c819-1363-4859-8fb9-f8cb104d49d2
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: 167.235.28.81
  port: 2226
  uuid: c98cf3bc-9f1a-41ae-a923-255ca07cb3aa
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: 9e85b4eb-f53d-457e-9385-454db3c1dcc1
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 190.93.246.246
  port: 8443
  uuid: b5441b0d-2147-4898-8a6a-9b2c87f58382
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560fp=chrome
    headers:
      Host: bitget1.asdasd.click
  servername: bitget1.asdasd.click
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: 5.10.244.109
  port: 443
  uuid: d69b938c-cbf4-4b61-aa97-e5762c304a25
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560fp=chrome
    headers:
      Host: madcity2.777999.lol
  servername: madcity2.777999.lol
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 35.174.9.231
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: whatismyipaddress.com
  port: 2096
  uuid: 2404f667-5969-4883-a71a-ea2e0db2d25b
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: fp=chrome
    headers:
      Host: wwwspeedtestnetwhiteberinsistomd6625996s08.gorgeserver1.ir
  servername: wwwspeedtestnetwhiteberinsistomd6625996s08.gorgeserver1.ir
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: 3.81.35.73
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: 3.84.217.14
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: 3.80.244.42
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: 34.229.104.253
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: 104.17.148.22
  port: 2082
  uuid: 2f3e929e-fe8c-44d5-b96b-6ec0e4b5e569
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /@spikevpn-@spikevpn-@spikevpn-@spikevpn-@spikevpn-@spikevpn?ed=2082
    headers:
      Host: novinsoft.ir.oradoshop.com.persiangsm.ir.digikala.com.abadis.ir.shad.ir.divar.ir.downloadly.com.aparat.com.cafebazar.ir.varzesh3.com.ninisite.com.abadis.ir.bama.ir.p30download.ir.telewebion.bmi.ir.shad.ir.mayket.com.ninisite.top.
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 100.24.71.29
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: 13.217.86.162
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a95b8225-c07b-47fe-b1e4-b1bda89c7f7c
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /-ViV2ry@V2RIRAN-TEL--@V2RIRAN-TEL--@V2RIRAN-TEL--@V2RIRAN-JOIN-@V2RIRAN-TEL--@V2RIRAN-JOIN-@V2RIRAN-TEL-@V2RIRAN-TEL--@V2RIRAN-JOIN-@V2RIRAN-TEL--@V2RIRAN?ed=2048
    headers:
      Host: Www.speedtest.net.sIgmasigmaboy.site.
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: 160.79.105.121
  port: 443
  uuid: 55520747-311e-4015-83ce-be46e2060ce3
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560security=tls
    headers:
      Host: cl.bgm2024.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: 34.203.207.10
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: 54.166.140.81
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: 54.90.211.248
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: 18.234.152.195
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: 98.81.177.222
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: 18.208.227.137
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: 34.207.180.2
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: 52.90.224.203
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-31
  type: vless
  server: 3.87.11.247
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-32
  type: vless
  server: 18.208.226.170
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-33
  type: vless
  server: 54.146.50.45
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-34
  type: vless
  server: 104.19.222.79
  port: 2096
  uuid: 2404f667-5969-4883-a71a-ea2e0db2d25b
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /security=tls
    headers:
      Host: wwwspeedtestnetwhiteberinsistomd6625996s08.gorgeserver1.ir
- name: ğŸŒ ASTRACAT-Tunels-35
  type: vless
  server: 104.19.223.79
  port: 2096
  uuid: 2404f667-5969-4883-a71a-ea2e0db2d25b
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /security=tls
    headers:
      Host: wwwspeedtestnetwhiteberinsistomd6625996s08.gorgeserver1.ir
- name: ğŸŒ ASTRACAT-Tunels-36
  type: vless
  server: 54.145.53.77
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-37
  type: vless
  server: 64.176.38.232
  port: 443
  uuid: e46d518d-4a20-4f9a-873d-a86e9455321c
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /e46d518d-4a20-4f9a-873d-a86e9455321c-vless?ed=2048security=tls
    headers:
      Host: lighter-missouri-hydrocodone-yeast.trycloudflare.com
- name: ğŸŒ ASTRACAT-Tunels-38
  type: vless
  server: 59.29.143.247
  port: 10894
  uuid: 794f9f41-92c9-4a78-8ffc-1f82cb48a4e2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /security=tls
    headers:
      Host: 0229.patterdeng.pp.ua
- name: ğŸŒ ASTRACAT-Tunels-39
  type: vless
  server: 154.197.108.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: ğŸŒ ASTRACAT-Tunels-40
  type: vless
  server: 160.79.104.11
  port: 443
  uuid: 55520747-311e-4015-83ce-be46e2060ce3
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560security=tls
    headers:
      Host: cl.bgm2024.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-41
  type: vless
  server: 108.162.198.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: ğŸŒ ASTRACAT-Tunels-42
  type: vless
  server: 13.217.2.236
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-43
  type: vless
  server: bestcf.030101.xyz
  port: 443
  uuid: 897a4bec-26b8-11e8-94be-00505695472c
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /bbs?ed=2048security=tls
    headers:
      Host: xv6.jpmj.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-44
  type: vless
  server: www.speedtest.net
  port: 8880
  uuid: e74c23fa-44c0-425e-812d-5e2df4487ced
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /telegram---Academi_vpn--telegram--Academi_vpn--telegram--Academi_vpn--telegram--Academi_vpn--telegram----Academi_vpn--Mystic_vpn?ed=2048
    headers:
      Host: de-snapp23.academigroup.ir.
- name: ğŸŒ ASTRACAT-Tunels-45
  type: vless
  server: 192.0.63.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: ğŸŒ ASTRACAT-Tunels-46
  type: vless
  server: 216.116.134.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: ğŸŒ ASTRACAT-Tunels-47
  type: vless
  server: 3.88.50.22
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-48
  type: vless
  server: 192.9.129.108
  port: 55573
  uuid: 6c7a6a6a-6a6a-4000-8000-000000000002
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /lzjjjjjjjjj666666666security=tls
    headers:
      Host: us2-hax.lzj520hxw.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-49
  type: vless
  server: 156.238.18.197
  port: 8880
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramU0001F1E8U0001F1F3 @MxlShare @WangCai2 /?ed=2560
    headers:
      Host: yd.laoyoutiao.link
- name: ğŸŒ ASTRACAT-Tunels-50
  type: vless
  server: 3.85.75.102
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-51
  type: vless
  server: 34.207.226.166
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-52
  type: vless
  server: 34.227.100.180
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-53
  type: vless
  server: 52.90.225.40
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-54
  type: vless
  server: 54.89.240.63
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-55
  type: vless
  server: 54.242.43.74
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-56
  type: vless
  server: 156.238.18.239
  port: 8880
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramU0001F1E8U0001F1F3 @MxlShare @WangCai2 /?ed=2560
    headers:
      Host: yd.laoyoutiao.link
- name: ğŸŒ ASTRACAT-Tunels-57
  type: vless
  server: 172.67.153.179
  port: 443
  uuid: 895552fa-6284-4c1d-ba00-3944e0c7c626
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /C1SukvGdr58yeduy9AOGfp=chrome
    headers:
      Host: 5er.www890604.dpdns.org
  servername: 5eR.WWW890604.dPDNS.OrG
- name: ğŸŒ ASTRACAT-Tunels-58
  type: vless
  server: 104.21.53.113
  port: 443
  uuid: 585acd30-52bf-4b70-a537-e13649fafefc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /rU9rSjDSOd4yY2fOefp=chrome
    headers:
      Host: bba.890601.pp.ua
  servername: bBA.890601.pP.UA
- name: ğŸŒ ASTRACAT-Tunels-59
  type: vless
  server: 34.229.111.223
  port: 443
  uuid: 7f93e196-1b2f-4a42-8051-5815554c05db
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-60
  type: vless
  server: 62.60.193.221
  port: 32774
  uuid: 6603a779-07c9-4bc9-8f61-4a09c238653a
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /6603a779fp=chrome
- name: ğŸŒ ASTRACAT-Tunels-61
  type: vless
  server: 162.159.248.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560fp=chrome
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: ğŸŒ ASTRACAT-Tunels-62
  type: vless
  server: 156.238.18.76
  port: 8880
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramğŸ‡¨ğŸ‡³ @MxlShare @WangCai2 /?ed=2560fp=chrome
    headers:
      Host: yd.laoyoutiao.link
- name: ğŸŒ ASTRACAT-Tunels-63
  type: vless
  server: 104.21.71.112
  port: 443
  uuid: 895552fa-6284-4c1d-ba00-3944e0c7c626
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /C1SukvGdr58yeduy9AOGfp=chrome
    headers:
      Host: cccvf34er4.288288.shop
  servername: CccVF34ER4.288288.sHop
- name: ğŸŒ ASTRACAT-Tunels-64
  type: vless
  server: 156.238.18.106
  port: 8880
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TelegramğŸ‡¨ğŸ‡³ @MxlShare @WangCai2 /?ed=2560fp=chrome
    headers:
      Host: yd.laoyoutiao.link
- name: ğŸŒ ASTRACAT-Tunels-65
  type: vless
  server: 212.183.88.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560fp=chrome
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: ğŸŒ ASTRACAT-Tunels-66
  type: vless
  server: 204.10.194.78
  port: 443
  uuid: b8bd42a9-551f-419d-b70d-4aefdd2cb074
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-67
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 9e769ce1-34be-4e3f-b0a6-823f30eb8f69
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /fp=chrome
    headers:
      Host: Ds807Ay6Vc.MaKeFoRlEsS.iNfO
  servername: Ds807Ay6Vc.MaKeFoRlEsS.iNfO
- name: ğŸŒ ASTRACAT-Tunels-68
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
  - ğŸŒ ASTRACAT-Tunels-31
  - ğŸŒ ASTRACAT-Tunels-32
  - ğŸŒ ASTRACAT-Tunels-33
  - ğŸŒ ASTRACAT-Tunels-34
  - ğŸŒ ASTRACAT-Tunels-35
  - ğŸŒ ASTRACAT-Tunels-36
  - ğŸŒ ASTRACAT-Tunels-37
  - ğŸŒ ASTRACAT-Tunels-38
  - ğŸŒ ASTRACAT-Tunels-39
  - ğŸŒ ASTRACAT-Tunels-40
  - ğŸŒ ASTRACAT-Tunels-41
  - ğŸŒ ASTRACAT-Tunels-42
  - ğŸŒ ASTRACAT-Tunels-43
  - ğŸŒ ASTRACAT-Tunels-44
  - ğŸŒ ASTRACAT-Tunels-45
  - ğŸŒ ASTRACAT-Tunels-46
  - ğŸŒ ASTRACAT-Tunels-47
  - ğŸŒ ASTRACAT-Tunels-48
  - ğŸŒ ASTRACAT-Tunels-49
  - ğŸŒ ASTRACAT-Tunels-50
  - ğŸŒ ASTRACAT-Tunels-51
  - ğŸŒ ASTRACAT-Tunels-52
  - ğŸŒ ASTRACAT-Tunels-53
  - ğŸŒ ASTRACAT-Tunels-54
  - ğŸŒ ASTRACAT-Tunels-55
  - ğŸŒ ASTRACAT-Tunels-56
  - ğŸŒ ASTRACAT-Tunels-57
  - ğŸŒ ASTRACAT-Tunels-58
  - ğŸŒ ASTRACAT-Tunels-59
  - ğŸŒ ASTRACAT-Tunels-60
  - ğŸŒ ASTRACAT-Tunels-61
  - ğŸŒ ASTRACAT-Tunels-62
  - ğŸŒ ASTRACAT-Tunels-63
  - ğŸŒ ASTRACAT-Tunels-64
  - ğŸŒ ASTRACAT-Tunels-65
  - ğŸŒ ASTRACAT-Tunels-66
  - ğŸŒ ASTRACAT-Tunels-67
  - ğŸŒ ASTRACAT-Tunels-68
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
