port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 88.216.187.57
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 199.34.228.185
  port: 443
  uuid: 15298f41-e80b-463a-b85b-0c903258a1c8
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: Telegram@WedBaZ/?ed
    headers:
      Host: d5.medicaltreatment.ir
  servername: d5.medicaltreatment.ir
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: 194.182.79.113
  port: 26468
  uuid: 495a1363-bd37-4f3a-861e-ffb1686cf4d5
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: 194.182.79.202
  port: 39049
  uuid: 5a29a909-66c2-476e-b851-73966c64023c
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: 194.182.79.7
  port: 19123
  uuid: 9e8c4793-f653-4839-9b8b-852496ef0e27
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: 45.140.167.253
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: 45.131.208.55
  port: 443
  uuid: 4d91916f-a7fd-419b-8b90-640bb8d4b3f2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /fJBvsL0uR2MtzRig
    headers:
      Host: myphotograpicpicture.ir
  servername: mypHOtoGRAPICpIctUre.iR
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: 104.31.16.95
  port: 2053
  uuid: 39a91eaf-a379-4fff-a9c8-1cb01442b76f
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ir.akcovufun.ir
  servername: ir.akcovufun.ir
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: 151.101.1.91
  port: 80
  uuid: 9b7645aa-91f4-4f6d-98d9-c22f4ce8784f
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=1024
    headers:
      Host: trickshow.silaber.net
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 94.130.187.47
  port: 2087
  uuid: 93cf17d3-2ffd-486b-9ea8-31ead0086137
  cipher: none
  tls: true
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: mainv2-ray.fast.hosting-ip.com
  port: 80
  uuid: 2ce4da59-28c7-41fa-9411-7dfde437c1cb
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray,TELEGRAM-@mainv2-ray?ed=2048
    headers:
      Host: namehmain.com
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 170.114.45.216
  port: 443
  uuid: 4d91916f-a7fd-419b-8b90-640bb8d4b3f2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /fJBvsL0uR2MtzRig
    headers:
      Host: myphotograpicpicture.ir
  servername: mypHOtoGRAPICpIctUre.iR
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: 150.241.101.16
  port: 443
  uuid: 588f094b-431b-422c-b80b-007945037072
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /websocket
    headers:
      Host: de09.abvpn.ru
  servername: de09.abvpn.ru
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: 157.180.28.52
  port: 2087
  uuid: f38e1473-0bb8-4190-8d49-ba1aaaf4e264
  cipher: none
  tls: true
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: de09.abvpn.ru
  port: 443
  uuid: 588f094b-431b-422c-b80b-007945037072
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /websocket
  servername: de09.abvpn.ru
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: 638822597953394880.hamedan-shledrc-acbs.info
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: de09.abvpn.ru
  port: 443
  uuid: 588f094b-431b-422c-b80b-007945037072
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /websocket
  servername: de09.abvpn.ru
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 141.101.122.211
  port: 2052
  uuid: 8247c690-5157-58f2-a7a2-21a78377bd98
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /vless#@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL
    headers:
      Host: sPeedtest2.sbs.us.vless.sitespeedtest.net
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: 37.152.173.139
  port: 8464
  uuid: 0f2e0501-5a4f-45b7-bd5e-209169cd34f9
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: 68.183.178.106
  port: 14798
  uuid: e7cd8b22-4b4e-4436-80b6-a8e091f1de17
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /FREE By Tharuwa (@z_z_z_zz_z) 0767597317
    headers:
      Host: zoom.us
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: cname.proxystore11.news
  port: 2087
  uuid: 37dd24e2-7f9b-45ba-b38c-ef7ed81890f6
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /prx11
    headers:
      Host: panel.proxystore11.news
  servername: panel.proxystore11.news
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: 13.61.114.31
  port: 22224
  uuid: 05519058-d2ac-4f28-9e4a-2b2a1386749e
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /telegram-channel-vlessconfig
  servername: trojan.burgerip.co.uk
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: 142.93.231.14
  port: 44111
  uuid: b3d82748-e641-430b-8779-7d36b83e9670
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: 45.82.251.176
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: 5.199.173.104
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: 45.8.211.230
  port: 443
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: CxNiMjJz.cAfUnEaR.InFo
  servername: CxNiMjJz.cAfUnEaR.InFo
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: 104.17.147.22
  port: 2096
  uuid: 96a1b724-68d2-4f4d-ab25-38ecd83577bc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ByRhHePn14.bLuEvIa.oRg
  servername: ByRhHePn14.bLuEvIa.oRg
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: 37.27.252.57
  port: 1519
  uuid: a8a424c8-0da6-44ee-ac8f-fa45e17ff2a1
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: 104.26.12.54
  port: 443
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hl.ylka.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-31
  type: vless
  server: 104.26.14.85
  port: 80
  uuid: d1260358-fce0-4ca5-b60e-2144bf101d05
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: CerEbraL-DecIsIoN.oNeEaT.cO.
- name: ğŸŒ ASTRACAT-Tunels-32
  type: vless
  server: 37.27.191.27
  port: 2172
  uuid: a8a424c8-0da6-44ee-ac8f-fa45e17ff2a1
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-33
  type: vless
  server: 94.130.107.86
  port: 2087
  uuid: f38e1473-0bb8-4190-8d49-ba1aaaf4e264
  cipher: none
  tls: true
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-34
  type: vless
  server: 89.27.8.25
  port: 80
  uuid: 504fa227-6493-4c4b-983c-4661c96a0e11
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: TelegramğŸ‡¨ğŸ‡³ @WangCai2 /?ed=2560
    headers:
      Host: vv.cscfwoker.fun
- name: ğŸŒ ASTRACAT-Tunels-35
  type: vless
  server: 84.32.9.37
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-36
  type: vless
  server: 94.228.164.249
  port: 80
  uuid: 504fa227-6493-4c4b-983c-4661c96a0e11
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: TelegramğŸ‡¨ğŸ‡³ @WangCai2 /?ed=2560
    headers:
      Host: vv.cscfwoker.fun
- name: ğŸŒ ASTRACAT-Tunels-37
  type: vless
  server: 151.101.64.155
  port: 80
  uuid: c082e5e6-defa-44e7-9f8b-3079bcc2ad26
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /-LiV2ry@LIGHTNING6-TEL--@LIGHTNING6-TEL--@LIGHTNING6-TEL--@LIGHTNING6-JOIN-@LIGHTNING6-TEL--@LIGHTNING6-JOIN-@LIGHTNING6-TEL-@LIGHTNING6-TEL--@LIGHTNING6-JOIN-@LIGHTNING6-TEL--@LIGHTNING6?ed=2048
    headers:
      Host: irancell.net.
- name: ğŸŒ ASTRACAT-Tunels-38
  type: vless
  server: 45.82.251.183
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-39
  type: vless
  server: 95.164.45.95
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-40
  type: vless
  server: 84.32.25.206
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-41
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /re5IzbZ9IZZMddtw?ed=2560/?TELEGRAM@MARAMBASHI_MARAMBASHI
    headers:
      Host: ipsycho.suex12.ir
- name: ğŸŒ ASTRACAT-Tunels-42
  type: vless
  server: 45.82.251.144
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-43
  type: vless
  server: 95.164.45.70
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-44
  type: vless
  server: 162.159.153.28
  port: 2083
  uuid: 6965e558-73a4-4808-a778-67e8a82d15aa
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: 1.659118019.uk
  servername: 1.659118019.uk
- name: ğŸŒ ASTRACAT-Tunels-45
  type: vless
  server: 45.80.110.75
  port: 8880
  uuid: 59860b15-b2d9-47f9-9b92-81bd1639fcc5
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: 23-lsjfjwiposkfls.hc2021.cfd
- name: ğŸŒ ASTRACAT-Tunels-46
  type: vless
  server: 5.10.245.75
  port: 443
  uuid: 4f2b9193-ab76-401f-a254-10982ac2881a
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hax-eu.lzj520hxw.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-47
  type: vless
  server: 104.16.147.32
  port: 443
  uuid: ecb790d4-36ca-4dfc-a142-b3a395d1c50d
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /ld?ed=2048
    headers:
      Host: ad1.xiqpanelz.com
  servername: ad1.xiqpanelz.com
- name: ğŸŒ ASTRACAT-Tunels-48
  type: vless
  server: 109.61.42.127
  port: 5511
  uuid: be68b2c8-835a-423d-a070-c0831e741b36
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-49
  type: vless
  server: 45.82.251.162
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-50
  type: vless
  server: 45.136.117.14
  port: 8880
  uuid: 39502dba-b0dc-59bb-b332-f75194b1689c
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-51
  type: vless
  server: 5.180.52.15
  port: 8880
  uuid: 21dfbe81-72d4-5ad5-8248-1e8d2cf13f8c
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-52
  type: vless
  server: 45.80.111.10
  port: 2052
  uuid: 45f01712-2893-53e3-8e6a-6b7c925021da
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /vless#@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL
    headers:
      Host: sPeedtest2.sbs.br.vless.sitespeedtest.net
- name: ğŸŒ ASTRACAT-Tunels-53
  type: vless
  server: 46.226.162.42
  port: 443
  uuid: 588f094b-431b-422c-b80b-007945037072
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /websocket
  servername: gbr01.abvpn.ru
- name: ğŸŒ ASTRACAT-Tunels-54
  type: vless
  server: 194.182.79.209
  port: 18411
  uuid: 44c83e4b-e35d-4bbe-8e69-56bbd8a366d3
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-55
  type: vless
  server: 45.12.30.46
  port: 2096
  uuid: 96a1b724-68d2-4f4d-ab25-38ecd83577bc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: LhCgBjGr29.vElTrIxS.OrG
  servername: LhCgBjGr29.vElTrIxS.OrG
- name: ğŸŒ ASTRACAT-Tunels-56
  type: vless
  server: 638817026935097685.amsterdam-shledrc-accc.info
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-57
  type: vless
  server: 194.182.79.242
  port: 45831
  uuid: 2fe2f807-e81b-4134-afb5-1d41564c73c7
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-58
  type: vless
  server: 5.253.30.9
  port: 8880
  uuid: dfcf379e-2d92-514e-84ca-77cdb1bd73c6
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-59
  type: vless
  server: pqh25v6.car25benz.shop
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-60
  type: vless
  server: pqh27v5.nature27.shop
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-61
  type: vless
  server: w.191266.xyz
  port: 443
  uuid: 114ad614-fe6c-4422-b0af-be6161190d7a
  cipher: none
  tls: true
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-62
  type: vless
  server: ddfr.191266.xyz
  port: 443
  uuid: 114ad614-fe6c-4422-b0af-be6161190d7a
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /C1SukvGdr58yeduy9AOG
    headers:
      Host: ddfr.191266.xyz
  servername: ddFR.191266.XYZ
- name: ğŸŒ ASTRACAT-Tunels-69
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
  - ğŸŒ ASTRACAT-Tunels-31
  - ğŸŒ ASTRACAT-Tunels-32
  - ğŸŒ ASTRACAT-Tunels-33
  - ğŸŒ ASTRACAT-Tunels-34
  - ğŸŒ ASTRACAT-Tunels-35
  - ğŸŒ ASTRACAT-Tunels-36
  - ğŸŒ ASTRACAT-Tunels-37
  - ğŸŒ ASTRACAT-Tunels-38
  - ğŸŒ ASTRACAT-Tunels-39
  - ğŸŒ ASTRACAT-Tunels-40
  - ğŸŒ ASTRACAT-Tunels-41
  - ğŸŒ ASTRACAT-Tunels-42
  - ğŸŒ ASTRACAT-Tunels-43
  - ğŸŒ ASTRACAT-Tunels-44
  - ğŸŒ ASTRACAT-Tunels-45
  - ğŸŒ ASTRACAT-Tunels-46
  - ğŸŒ ASTRACAT-Tunels-47
  - ğŸŒ ASTRACAT-Tunels-48
  - ğŸŒ ASTRACAT-Tunels-49
  - ğŸŒ ASTRACAT-Tunels-50
  - ğŸŒ ASTRACAT-Tunels-51
  - ğŸŒ ASTRACAT-Tunels-52
  - ğŸŒ ASTRACAT-Tunels-53
  - ğŸŒ ASTRACAT-Tunels-54
  - ğŸŒ ASTRACAT-Tunels-55
  - ğŸŒ ASTRACAT-Tunels-56
  - ğŸŒ ASTRACAT-Tunels-57
  - ğŸŒ ASTRACAT-Tunels-58
  - ğŸŒ ASTRACAT-Tunels-59
  - ğŸŒ ASTRACAT-Tunels-60
  - ğŸŒ ASTRACAT-Tunels-61
  - ğŸŒ ASTRACAT-Tunels-62
  - ğŸŒ ASTRACAT-Tunels-69
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
