port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: d300ae15-2ba2-4f91-b1b0-b4510912e4cc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /admin
    headers:
      Host: 2free2.aparatir.xyz
  servername: 2free2.aparatir.xyz
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: 101reel.com
  port: 80
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@MARAMBASHI_MARAMBASHI_MARAMBASHI
    headers:
      Host: havvas.shohreh.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: 62.60.233.250
  port: 443
  uuid: fd0cdd44-2361-11f0-9970-45e1d80c4039
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: kernel.panel.cactusv2.xyz
  port: 4434
  uuid: 346264b7-975c-4891-8f7b-dcd6e5707a42
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: viop.fast.hosting-ip.com
  port: 80
  uuid: 7fa08b3d-86d8-4b14-92b3-4c56a83f027d
  cipher: none
  tls: false
  network: xhttp
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: all32-vip.f-sub.com
  port: 2434
  uuid: 738c5a04-817a-4f50-b327-893595010155
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 91.99.190.38
  port: 51615
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: c51.aminzing.lol
  port: 443
  uuid: 2de98c6e-319d-4fd1-81ba-82237c44ed36
  cipher: none
  tls: true
  network: httpupgrade
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: 638976291607120660.oslo-drcn-aaaae.info
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: 638976764967211989.gorgan-drcn-aaaae.info
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: 638974363192993928.budapest-blkaft-aaav.info
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: 86.104.74.62
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: 185.234.64.63
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: 185.234.64.5
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 40.233.118.103
  port: 42557
  uuid: 2429bee3-e0c1-47dd-b420-75e6512b184b
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: axe.soyet2j.ir
  port: 2087
  uuid: 4cf3c711-58e1-4abb-a628-3b48bdba8052
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /index.html?ed=2560fp=chrome
    headers:
      Host: latte.gejeh683bm.ir
  servername: latte.gejeh683bm.ir.
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: refreshcloud-ger.parsgit.com
  port: 4040
  uuid: ba29c23c-2174-46c2-9c99-65cacc2237df
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /admin?ed=1024
    headers:
      Host: refreshcloud-ger.parsgit.com.
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: 77.110.119.225
  port: 443
  uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: russia22.clearorbitllc.com
  port: 443
  uuid: 5c1bc547-6ed3-4234-873e-966d9eef5d27
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: fi.aliusvpn.ru
  port: 8443
  uuid: 1bbc55ca-3200-48d8-bffe-948788d72ed0
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: usa.savanet.pro
  port: 443
  uuid: 87eff1bd-d55f-4df2-a5ad-863368a16cb7
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: freeyx.cloudflare88.eu.org
  port: 443
  uuid: bda91ce0-d0d7-4d6a-a6e2-10860f655cf5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /announcement?ed=2048fp=random
    headers:
      Host: do-sfo3.862400.xyz
  servername: do-sfo3.862400.xyz
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: freeyx.cloudflare88.eu.org
  port: 443
  uuid: bda91ce0-d0d7-4d6a-a6e2-10860f655cf5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /announcement?ed=2048fp=random
    headers:
      Host: do-fra1.862400.xyz
  servername: do-fra1.862400.xyz
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: freeyx.cloudflare88.eu.org
  port: 443
  uuid: bda91ce0-d0d7-4d6a-a6e2-10860f655cf5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /announcement?ed=2048fp=random
    headers:
      Host: do-syd1.862400.xyz
  servername: do-syd1.862400.xyz
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: 172.66.44.183
  port: 443
  uuid: c3975f60-60d4-4f14-9780-070ce18c1dda
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /doa9bvfjd83ix3v9?ed=2560fp=chrome
    headers:
      Host: a-4km.pages.dev
  servername: a-4km.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: b1addf1e-6c1d-4410-bfa5-cf26328319d9
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /CmxkS1704Zcx8p3M?ed=2560fp=randomized
    headers:
      Host: 0HvsNO270bvRxG6EKbY8uMsQn-6941Fa.paGeS.dEV
  servername: 0HvsNO270bvRxG6EKbY8uMsQn-6941Fa.paGeS.dEV
- name: ğŸŒ ASTRACAT-Tunels-31
  type: vless
  server: www.visa.com.sg
  port: 8443
  uuid: 86c50e3a-5b87-49dd-bd20-03c7f2735e40
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560fp=random
    headers:
      Host: azadnet-2f7.pages.dev
  servername: azadnet-2f7.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-32
  type: vless
  server: aliakb3435.pages.dev
  port: 443
  uuid: 97c4550f-8ecc-42fa-ae66-3b550c986cd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /fp=chrome
    headers:
      Host: aliakb3435.pages.dev
  servername: aliakb3435.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-33
  type: vless
  server: usa32.clearorbitllc.com
  port: 443
  uuid: 9daf8f3e-089b-4989-9502-dd3d727edb6c
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-34
  type: vless
  server: 69.84.182.18
  port: 443
  uuid: a25ff90c-964c-485a-b72a-858864a27dc0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /profile/sharenodesecurity=tls
    headers:
      Host: cdn-node-oss-63.paofu.de
- name: ğŸŒ ASTRACAT-Tunels-35
  type: vless
  server: freev2.cloudflare.182682.xyz
  port: 443
  uuid: bda91ce0-d0d7-4d6a-a6e2-10860f655cf5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /announcementfp=random
    headers:
      Host: do-sgp1.862400.xyz
  servername: do-sgp1.862400.xyz
- name: ğŸŒ ASTRACAT-Tunels-36
  type: vless
  server: ct.877774.xyz
  port: 443
  uuid: bda91ce0-d0d7-4d6a-a6e2-10860f655cf5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /announcementfp=random
    headers:
      Host: do-lon1.862400.xyz
  servername: do-lon1.862400.xyz
- name: ğŸŒ ASTRACAT-Tunels-37
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
  - ğŸŒ ASTRACAT-Tunels-31
  - ğŸŒ ASTRACAT-Tunels-32
  - ğŸŒ ASTRACAT-Tunels-33
  - ğŸŒ ASTRACAT-Tunels-34
  - ğŸŒ ASTRACAT-Tunels-35
  - ğŸŒ ASTRACAT-Tunels-36
  - ğŸŒ ASTRACAT-Tunels-37
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
