port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-1
  type: vless
  server: 77.90.41.131
  port: 10878
  uuid: 32e9e2c6-1f76-4ff5-9681-c98a5961e7f6
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-2
  type: vless
  server: 185.39.207.121
  port: 443
  uuid: 6035325d-399a-5148-9126-29cedfd5966a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-3
  type: vless
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  port: 443
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-4
  type: vless
  server: hybrid.arvancloud.online
  port: 44443
  uuid: 53fff6cc-b4ec-43e8-ade5-e0c42972fc33
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-5
  type: vless
  server: 164.92.145.207
  port: 26129
  uuid: acc1a984-2a8b-4dce-ab45-d294e6f3e451
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /winrar
    headers:
      Host: soft98.ir
- name: ğŸŒ ASTRACAT-Tunels-6
  type: vless
  server: 159.223.235.238
  port: 22231
  uuid: d39ae55e-234b-4365-9263-a7e20ebbe233
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-7
  type: vless
  server: 5.180.52.11
  port: 443
  uuid: 6035325d-399a-5148-9126-29cedfd5966a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-8
  type: vless
  server: 91.219.23.100
  port: 443
  uuid: 77b3bda7-4ee3-4c99-bad1-a935f7e027c8
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: 91.219.23.129
  port: 443
  uuid: 77b3bda7-4ee3-4c99-bad1-a935f7e027c8
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: deu316.unlocknet.org
  port: 443
  uuid: 77b3bda7-4ee3-4c99-bad1-a935f7e027c8
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: 91.219.23.90
  port: 443
  uuid: 77b3bda7-4ee3-4c99-bad1-a935f7e027c8
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 94.26.228.68
  port: 443
  uuid: 5475990d-e0ce-46ea-95e5-50f9e4879af9
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: 91.219.23.102
  port: 443
  uuid: 77b3bda7-4ee3-4c99-bad1-a935f7e027c8
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: 38.244.39.95
  port: 17779
  uuid: a83d7ca8-9ff7-3c65-ace5-b2f53dd5b1dc
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: 1002.952326.xyz
  port: 10001
  uuid: 68bec4db-a813-417e-85ff-0367e8f3cf22
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: 166.88.142.46
  port: 10101
  uuid: b0797d01-63a2-4a19-8ca1-674a09eca4f4
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: 172.245.251.10
  port: 8443
  uuid: 9b3d65ab-576c-4750-9cb3-bb41c12c085e
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: 160.25.74.112
  port: 10109
  uuid: 2a0ce0d5-cd10-4f7a-9c86-cf20fb2a9ce3
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 160.25.74.112
  port: 10109
  uuid: ef9ffa72-b723-4382-a7d6-88e2cd2aa773
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-1
  - ğŸŒ ASTRACAT-Tunels-2
  - ğŸŒ ASTRACAT-Tunels-3
  - ğŸŒ ASTRACAT-Tunels-4
  - ğŸŒ ASTRACAT-Tunels-5
  - ğŸŒ ASTRACAT-Tunels-6
  - ğŸŒ ASTRACAT-Tunels-7
  - ğŸŒ ASTRACAT-Tunels-8
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
