port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: ğŸŒ ASTRACAT-Tunels-9
  type: vless
  server: deu106.worldunbound.org
  port: 443
  uuid: 0b23f113-6bd4-42a6-887c-a47381f06f5c
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-10
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-11
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-12
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: d300ae15-2ba2-4f91-b1b0-b4510912e4cc
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /admin
    headers:
      Host: 2free2.aparatir.xyz
  servername: 2free2.aparatir.xyz
- name: ğŸŒ ASTRACAT-Tunels-13
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-14
  type: vless
  server: 101reel.com
  port: 80
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@MARAMBASHI_MARAMBASHI_MARAMBASHI
    headers:
      Host: havvas.shohreh.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-15
  type: vless
  server: 62.60.233.250
  port: 443
  uuid: fd0cdd44-2361-11f0-9970-45e1d80c4039
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-16
  type: vless
  server: kernel.panel.cactusv2.xyz
  port: 4434
  uuid: 346264b7-975c-4891-8f7b-dcd6e5707a42
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-17
  type: vless
  server: viop.fast.hosting-ip.com
  port: 80
  uuid: 7fa08b3d-86d8-4b14-92b3-4c56a83f027d
  cipher: none
  tls: false
  network: xhttp
- name: ğŸŒ ASTRACAT-Tunels-18
  type: vless
  server: all32-vip.f-sub.com
  port: 2434
  uuid: 738c5a04-817a-4f50-b327-893595010155
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-19
  type: vless
  server: 91.99.190.38
  port: 51615
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  cipher: none
  tls: false
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-20
  type: vless
  server: c51.aminzing.lol
  port: 443
  uuid: 2de98c6e-319d-4fd1-81ba-82237c44ed36
  cipher: none
  tls: true
  network: httpupgrade
- name: ğŸŒ ASTRACAT-Tunels-21
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ğŸŒ ASTRACAT-Tunels-22
  type: vless
  server: 104.26.14.69
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-23
  type: vless
  server: privasi.turah.my.id
  port: 443
  uuid: 0fbf4f81-2598-4b6a-a623-0ead4cb9efa8
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /Free-CF-Proxy-AD192.3.113.4-19318
    headers:
      Host: privasi.turah.my.id
  servername: privasi.turah.my.id
- name: ğŸŒ ASTRACAT-Tunels-24
  type: vless
  server: 104.21.67.12
  port: 443
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
  servername: carlotta.shoorekeeper.cloudns.org
- name: ğŸŒ ASTRACAT-Tunels-25
  type: vless
  server: 104.16.108.84
  port: 443
  uuid: a89357b8-a501-46bd-ac6d-c0f37f1fd0f5
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: shutu.pages.dev
  servername: shutu.pages.dev
- name: ğŸŒ ASTRACAT-Tunels-26
  type: vless
  server: communal-loss.oneeat.co
  port: 80
  uuid: a2af50d9-09c7-4a44-90d0-42da35923e9e
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
- name: ğŸŒ ASTRACAT-Tunels-27
  type: vless
  server: 45.131.4.85
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: ğŸŒ ASTRACAT-Tunels-28
  type: vless
  server: pqh25v7.waipdirect.shop
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  cipher: none
  tls: false
  network: grpc
- name: ğŸŒ ASTRACAT-Tunels-29
  type: vless
  server: 185.39.207.121
  port: 443
  uuid: 6035325d-399a-5148-9126-29cedfd5966a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-30
  type: vless
  server: 185.152.94.10
  port: 443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-31
  type: vless
  server: 185.152.94.10
  port: 1443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-32
  type: vless
  server: 213.232.120.10
  port: 1443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-33
  type: vless
  server: 147.78.180.10
  port: 1443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-34
  type: vless
  server: 147.78.180.10
  port: 443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-35
  type: vless
  server: 213.232.123.10
  port: 1443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-36
  type: vless
  server: 213.232.123.10
  port: 443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-37
  type: vless
  server: 92.118.112.83
  port: 443
  uuid: 6035325d-399a-5148-9126-29cedfd5966a
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-38
  type: vless
  server: 85.239.56.10
  port: 443
  uuid: 3c7a1227-5383-3a19-7084-76624ec8f84f
  cipher: none
  tls: true
  network: tcp
- name: ğŸŒ ASTRACAT-Tunels-39
  type: vless
  server: Everyday-VPN.Telegram-Channel
  port: 443
  uuid: 11111111-2222-1111-1111-111111111111
  cipher: none
  tls: true
  network: grpc
proxy-groups:
- name: ğŸš€ ASTRACAT-Tunels-Group
  type: select
  proxies:
  - ğŸŒ ASTRACAT-Tunels-9
  - ğŸŒ ASTRACAT-Tunels-10
  - ğŸŒ ASTRACAT-Tunels-11
  - ğŸŒ ASTRACAT-Tunels-12
  - ğŸŒ ASTRACAT-Tunels-13
  - ğŸŒ ASTRACAT-Tunels-14
  - ğŸŒ ASTRACAT-Tunels-15
  - ğŸŒ ASTRACAT-Tunels-16
  - ğŸŒ ASTRACAT-Tunels-17
  - ğŸŒ ASTRACAT-Tunels-18
  - ğŸŒ ASTRACAT-Tunels-19
  - ğŸŒ ASTRACAT-Tunels-20
  - ğŸŒ ASTRACAT-Tunels-21
  - ğŸŒ ASTRACAT-Tunels-22
  - ğŸŒ ASTRACAT-Tunels-23
  - ğŸŒ ASTRACAT-Tunels-24
  - ğŸŒ ASTRACAT-Tunels-25
  - ğŸŒ ASTRACAT-Tunels-26
  - ğŸŒ ASTRACAT-Tunels-27
  - ğŸŒ ASTRACAT-Tunels-28
  - ğŸŒ ASTRACAT-Tunels-29
  - ğŸŒ ASTRACAT-Tunels-30
  - ğŸŒ ASTRACAT-Tunels-31
  - ğŸŒ ASTRACAT-Tunels-32
  - ğŸŒ ASTRACAT-Tunels-33
  - ğŸŒ ASTRACAT-Tunels-34
  - ğŸŒ ASTRACAT-Tunels-35
  - ğŸŒ ASTRACAT-Tunels-36
  - ğŸŒ ASTRACAT-Tunels-37
  - ğŸŒ ASTRACAT-Tunels-38
  - ğŸŒ ASTRACAT-Tunels-39
rules:
- MATCH,ğŸš€ ASTRACAT-Tunels-Group
dns:
  enable: true
  ipv6: false
  nameserver:
  - 85.209.2.112
